name: pyplane
summary: PyPLANE
description: 
  An open source replacement to the traditional DFIELD and PPLANE applications for solving systems of ODEs
base: core18
icon: snap/gui/pyplane.png
version: "git"

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all

  pyplane:
    source: .
    plugin: python
    python-version: "python3"
    python-packages:
      - numpy
      - sympy
      - scipy
      - matplotlib
      - pyqt5
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libgl1-mesa-glx
      - libegl1-mesa
      - libqt53danimation5
      - libqt53dcore5
      - libqt53dextras5
      - libqt53dinput5
      - libqt53dlogic5
      - libqt53dquick5
      - libqt53dquickscene2d5
      - libqt53drender5
      - libqt5gui5
      - libqt5texttospeech5
      - libqt5webengine5
      - libqt5webenginecore5
      - libqt5webview5
      - libxcomposite1
      - libasound2
      - libatk1.0-0
      - libcairo-gobject2
      - libcairo2
      - libcups2
      - libfontconfig1
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libodbc1
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpq5
      - libpulse-mainloop-glib0
      - libpulse0
      - libspeechd2
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libxkbcommon-x11-0
      - libxkbcommon0
    after: [desktop-qt5]
    
apps:
  pyplane:
    adapter: full
    command: bin/run
    command-chain:
      - bin/desktop-launch
    plugs: [unity7, x11, wayland, opengl, desktop, desktop-legacy]

confinement: strict
