name: pyplane
summary: PyPLANE
description: 
  An open source replacement to the traditional DFIELD and PPLANE applications for solving systems of ODEs
base: core18
version: "almost0.1"

parts:
  pyplane:
    source: . 
    plugin: python
    python-version: "python3"
    python-packages:
      - numpy
      - sympy
      - scipy
      - matplotlib
      - pyqt5
    
apps:
  pyplane:
    command: run_gui

confinement: strict
